include: package:lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

#   exclude:
#     - path/to/excluded/files/**

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    - package_names

    - avoid_empty_else
    - avoid_return_types_on_setters
    - cancel_subscriptions
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
    - close_sinks
    - no_adjacent_strings_in_list

    - unnecessary_statements
    - unnecessary_null_in_if_null_operators
    - unnecessary_null_aware_assignments
    - unnecessary_new
    - unnecessary_lambdas
    - unnecessary_const

    - void_checks

    - prefer_is_empty
    - prefer_is_not_empty

    - slash_for_doc_comments
    - prefer_contains
    - prefer_final_fields
    - prefer_final_locals

    - always_put_control_body_on_new_line
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_annotating_with_dynamic
    - avoid_classes_with_only_static_members
    - avoid_bool_literals_in_conditional_expressions
    - avoid_double_and_int_checks
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_positional_boolean_parameters
    - avoid_renaming_method_parameters
    - avoid_returning_null

    - camel_case_types
    - constant_identifier_names
    - empty_constructor_bodies
    - cascade_invocations
    - omit_local_variable_types

    - prefer_single_quotes
    - package_api_docs
#    - public_member_api_docs
